#!/bin/bash

# sync-ai-skills.sh
# Antigravityのカスタムスキルをマージし、Claude, Copilot, Cursor(Codex), agy (Antigravity CLI) にグローバルおよびローカル適用するスクリプト

set -e

SKILLS_DIR="$HOME/.gemini/config/skills"
OUTPUT_DIR="$HOME/.config"
MASTER_RULES_FILE="$OUTPUT_DIR/ai-global-rules.md"
CURSOR_RULES_FILE="$HOME/.cursorrules"
AGY_CONFIG_DIR="$HOME/.gemini/config"
AGY_RULES_FILE="$AGY_CONFIG_DIR/GEMINI.md"
CLAUDE_CODE_RULES_FILE="$HOME/.claudecode.md"

# 1. 出力ディレクトリの作成
mkdir -p "$OUTPUT_DIR"
mkdir -p "$AGY_CONFIG_DIR"

echo "=== 1. Skills のスキャンとマージを開始します ==="

# マージファイルの初期化
cat << 'EOF' > "$MASTER_RULES_FILE"
# Global AI Rules & Custom Skills

This file is automatically generated by sync-ai-skills.sh.
It aggregates global agent skills for Claude Code, GitHub Copilot, Cursor (Codex), and Antigravity (agy).

EOF

# 各 SKILL.md をスキャンしてマージ
if [ -d "$SKILLS_DIR" ]; then
  # ディレクトリ一覧を取得し、SKILL.md があるものを探す
  find "$SKILLS_DIR" -type d -maxdepth 1 | while read -r skill_path; do
    skill_name=$(basename "$skill_path")
    # 自分自身（skillsディレクトリそのもの）はスキップ
    if [ "$skill_name" = "skills" ] || [ -z "$skill_name" ]; then
      continue
    fi

    skill_file="$skill_path/SKILL.md"
    if [ -f "$skill_file" ]; then
      echo "Processing skill: $skill_name"
      
      # YAMLフロントマッターを除去してマージ
      # awkを使って最初の --- と二番目の --- の間を除去する
      echo "" >> "$MASTER_RULES_FILE"
      echo "---" >> "$MASTER_RULES_FILE"
      echo "## Skill: $skill_name" >> "$MASTER_RULES_FILE"
      echo "" >> "$MASTER_RULES_FILE"
      
      # フロントマッターを除去して追記
      awk '
        BEGIN { in_yaml=0; yaml_count=0 }
        /^---$/ {
          yaml_count++
          if (yaml_count == 1) { in_yaml=1; next }
          if (yaml_count == 2) { in_yaml=0; next }
        }
        {
          if (!in_yaml) { print }
        }
      ' "$skill_file" >> "$MASTER_RULES_FILE"
      
      echo "" >> "$MASTER_RULES_FILE"
    fi
  done
else
  echo "Error: Skills directory not found at $SKILLS_DIR"
  exit 1
fi

echo "Master rules file created: $MASTER_RULES_FILE"

# 2. Cursor (Codex) 向けのグローバル設定 (ホームディレクトリの .cursorrules)
echo "=== 2. Cursor (Codex) へのグローバル設定 ==="
ln -sf "$MASTER_RULES_FILE" "$CURSOR_RULES_FILE"
echo "Cursor global rules set: $CURSOR_RULES_FILE -> $MASTER_RULES_FILE"

# 3. agy (Antigravity CLI) 向けのグローバル設定 (GEMINI.md)
echo "=== 3. agy (Antigravity CLI) へのグローバル設定 ==="
ln -sf "$MASTER_RULES_FILE" "$AGY_RULES_FILE"
echo "agy global rules set: $AGY_RULES_FILE -> $MASTER_RULES_FILE"

# 4. Claude Code 向けのグローバル設定 (.claudecode.md)
echo "=== 4. Claude Code へのグローバル設定 ==="
ln -sf "$MASTER_RULES_FILE" "$CLAUDE_CODE_RULES_FILE"
echo "Claude Code global rules set: $CLAUDE_CODE_RULES_FILE -> $MASTER_RULES_FILE"

# 5. VS Code / GitHub Copilot へのグローバル設定
echo "=== 5. VS Code / GitHub Copilot への設定を適用します ==="

# Node.js を使って settings.json を安全に書き換えるスクリプトを実行
node - << 'EOF'
const fs = require('fs');
const path = require('path');

const settingsPath = path.join(
  process.env.HOME,
  'Library/Application Support/Code/User/settings.json'
);
const rulesPath = path.join(process.env.HOME, '.config/ai-global-rules.md');

if (!fs.existsSync(settingsPath)) {
  console.log('VS Code settings.json not found at ' + settingsPath + '. Skipped Copilot registration.');
  process.exit(0);
}

// バックアップの作成
fs.copyFileSync(settingsPath, settingsPath + '.backup');
console.log('VS Code settings.json backed up to settings.json.backup');

let settingsText = fs.readFileSync(settingsPath, 'utf8');
let settings = {};

try {
  // コメント付きJSONをパースするために、簡単なコメント削除処理を行う
  const cleanJson = settingsText.replace(/\/\*[\s\S]*?\*\/|([^\\:]|^)\/\/.*$/gm, '$1');
  settings = JSON.parse(cleanJson);
} catch (e) {
  console.error('Error parsing settings.json. Restoring backup...');
  fs.copyFileSync(settingsPath + '.backup', settingsPath);
  process.exit(1);
}

const key = 'github.copilot.chat.codeGeneration.instructions';
if (!settings[key]) {
  settings[key] = [];
}

// 既に登録されているか確認
const exists = settings[key].some(item => item.filePath === rulesPath || item.file === rulesPath);
if (!exists) {
  settings[key].push({ filePath: rulesPath });
  fs.writeFileSync(settingsPath, JSON.stringify(settings, null, 2), 'utf8');
  console.log('Successfully registered to GitHub Copilot settings.');
} else {
  console.log('GitHub Copilot settings already registered.');
}
EOF

# 6. 同期完了
echo "=== 同期完了 ==="
echo "全ツールのグローバル適用が完了しました。"
echo ""
echo "カレントプロジェクト（Claude Code や Cursorのローカル設定）に"
echo "このスキルルールを即時適用するには、以下のコマンドを実行してください："
echo "--------------------------------------------------------"
echo "ln -sf $MASTER_RULES_FILE ./CLAUDE.md"
echo "ln -sf $MASTER_RULES_FILE ./.cursorrules"
echo "--------------------------------------------------------"
