#!/usr/bin/env bash
# Maintainer utility: merge global SKILL.md files and link them to AI tools.

set -euo pipefail

apply_changes=false
case "${1:-}" in
  "") ;;
  --apply) apply_changes=true ;;
  --help|-h)
    echo "Usage: $0 [--apply]"
    echo "Without --apply, prints a dry-run and does not change any files."
    exit 0
    ;;
  *)
    echo "Unknown option: $1" >&2
    echo "Usage: $0 [--apply]" >&2
    exit 2
    ;;
esac

skills_dir="$HOME/.gemini/config/skills"
output_dir="$HOME/.config"
master_rules_file="$output_dir/ai-global-rules.md"
cursor_rules_file="$HOME/.cursorrules"
agy_rules_file="$HOME/.gemini/config/GEMINI.md"
claude_code_rules_file="$HOME/.claudecode.md"

if [ ! -d "$skills_dir" ]; then
  echo "Skills directory not found: $skills_dir" >&2
  exit 1
fi

if [ "$apply_changes" = false ]; then
  echo "[dry-run] No files will be changed."
  echo "Would merge SKILL.md files from: $skills_dir"
  echo "Would back up and replace:"
  echo "  $master_rules_file"
  echo "  $cursor_rules_file"
  echo "  $agy_rules_file"
  echo "  $claude_code_rules_file"
  echo "Run '$0 --apply' to perform these changes."
  exit 0
fi

timestamp="$(date +%Y%m%d-%H%M%S)-$$"

backup_and_link() {
  target=$1
  mkdir -p "$(dirname "$target")"
  if [ -e "$target" ] || [ -L "$target" ]; then
    backup_path="$target.backup-$timestamp"
    mv "$target" "$backup_path"
    echo "Backed up: $target -> $backup_path"
  fi
  ln -s "$master_rules_file" "$target"
  echo "Linked: $target -> $master_rules_file"
}

mkdir -p "$output_dir"
temporary_rules_file="$output_dir/.ai-global-rules.md.tmp-$timestamp"
trap 'rm -f "$temporary_rules_file"' EXIT
{
  echo "# Global AI Rules & Custom Skills"
  echo ""
  echo "Generated by sync-ai-skills.sh from $skills_dir."

  for skill_path in "$skills_dir"/*; do
    [ -d "$skill_path" ] || continue
    skill_file="$skill_path/SKILL.md"
    [ -f "$skill_file" ] || continue

    skill_name=$(basename "$skill_path")
    echo ""
    echo "---"
    echo "## Skill: $skill_name"
    echo ""
    awk '
      BEGIN { in_yaml=0; yaml_count=0 }
      /^---$/ {
        yaml_count++
        if (yaml_count == 1) { in_yaml=1; next }
        if (yaml_count == 2) { in_yaml=0; next }
      }
      !in_yaml { print }
    ' "$skill_file"
  done
} > "$temporary_rules_file"

if [ -e "$master_rules_file" ] || [ -L "$master_rules_file" ]; then
  master_backup_path="$master_rules_file.backup-$timestamp"
  mv "$master_rules_file" "$master_backup_path"
  echo "Backed up: $master_rules_file -> $master_backup_path"
fi
mv "$temporary_rules_file" "$master_rules_file"
trap - EXIT

backup_and_link "$cursor_rules_file"
backup_and_link "$agy_rules_file"
backup_and_link "$claude_code_rules_file"

echo "Applied global rules. VS Code settings are intentionally unchanged."
